### ISSUE TITLE
Application description is truncated

### ISSUE THREAD

**Issue by henare** [LoveMyData/manly#1]
e.g. http://da.manly.nsw.gov.au/MasterViewUI/Modules/Applicationmaster/default.aspx?page=wrapper&key=010.2014.00000063.002

The scraped description is:

> Section 96 to modify approved Alterations and additions to the ground

it should be...

> Section 96 to modify approved Alterations and additions to the ground and first floors of the existing dwelling and to the existing carport.- involving – modifications to windows and finishes; addition of skylights and dwarf wall near carport - Part 2

**Comment by LoveMyData** [comment]
Check this out, it should be fixed. https://github.com/LoveMyData/manly/commit/11fbac337e183eba2b634b388a6b0c6b562e7299
